from typing import Literal

WAWebModuleType = Literal[
    "WAWebCollections",
    "WAWebSocketModel.Socket",
    "WAWebBlockContactAction",
    "WAWebConnModel.Conn",
    "WAWebCmd.Cmd",
    "WAWebDownloadManager.downloadManager",
    "WAWebGroupQueryJob.queryAndUpdateGroupMetadataById",
    "WAWebPrepRawMedia",
    "WAWebMediaStorage",
    "WAWebMmsMediaTypes",
    "WAWebMediaMmsV4Upload",
    "WAWebMsgKey",
    "WAWebMediaOpaqueData",
    "WAWebBizProductCatalogBridge",
    "WAWebBizOrderBridge",
    "WAWebChatClearBridge",
    "WAWebDeleteChatAction",
    "WAWebSendMsgChatAction",
    "WAWebSendMessageEditAction",
    "WAWebUpdateUnreadChatAction",
    "WAWebUserPrefsMeUser",
    "WAWebContactGetters",
    "WAWebWid",
    "WALinkify",
    "WAWebWidFactory",
    "WAWebContactProfilePicThumbBridge",
    "WAWebPresenceChatAction",
    "WAWebChatStateBridge",
    "WAWebFindCommonGroupsContactAction.findCommonGroups",
    "WAWebContactStatusBridge",
    "WAWebChatLoadMessages",
    "WAWebSendReactionMsgAction.sendReactionToMsg",
    "WAWebDBCreateOrUpdateReactions",
    "WAWebGetEphemeralFieldsMsgActionsUtils",
    "WAWebMsgActionCapability",
    "WAWebQuotedMsgModelUtils",
    "WAWebLinkPreviewChatAction",
    "WADeprecatedSendIq",
    "WAWap",
    "WAWebChatMessageSearch",
    "WAWebDrawerManager.DrawerManager",
    "WAWebApiContact",
    "WAWebWidToJid",
    "WAWebJidToWid",
    "WAWebApiMessageInfoStore.queryMsgInfo",
    "WAWebQueryExistsJob.queryWidExists",
    "WAWebMsgReply",
    "WAWebBotMessageSecret",
    "WAWebBotProfileCollection",
    "WAWebContactCollection.ContactCollection",
    "WAWebApiDeviceList",
    "WAWebSendNonMessageDataRequest",
    "WAWebAddonReactionTableMode.reactionTableMode",
    "WAWebAddonPollVoteTableMode.pollVoteTableMode",
    "WAWebSendPinMessageAction",
    "WAWebChatGetters",
    "WAWebUploadManager",
    "WAWebStreamModel",
    "WAWebFindChatAction",
]


# got these from whatsapp-web.js 
WAWEB_STORE = {
    "Collections": "WAWebCollections",
    "AppState": "WAWebSocketModel.Socket",
    "BlockContact": "WAWebBlockContactAction",
    "Connection": "WAWebConnModel.Conn",
    "Commands": "WAWebCmd.Cmd",
    "DownloadManager": "WAWebDownloadManager.downloadManager",
    "GroupUpdater": "WAWebGroupQueryJob.queryAndUpdateGroupMetadataById",
    "MediaPrep": "WAWebPrepRawMedia",
    "MediaStorage": "WAWebMediaStorage",
    "MediaTypes": "WAWebMmsMediaTypes",
    "MediaUpload": "WAWebMediaMmsV4Upload",
    "MessageKey": "WAWebMsgKey",
    "OpaqueData": "WAWebMediaOpaqueData",
    "ProductCatalog": "WAWebBizProductCatalogBridge",
    "OrderQuery": "WAWebBizOrderBridge",
    "ClearChat": "WAWebChatClearBridge",
    "DeleteChat": "WAWebDeleteChatAction",
    "SendMessage": "WAWebSendMsgChatAction",
    "EditMessage": "WAWebSendMessageEditAction",
    "MarkSeen": "WAWebUpdateUnreadChatAction",
    "CurrentUser": "WAWebUserPrefsMeUser",
    "ContactHelpers": "WAWebContactGetters",
    "UserID": "WAWebWid",
    "Validators": "WALinkify",
    "WidFactory": "WAWebWidFactory",
    "ProfilePic": "WAWebContactProfilePicThumbBridge",
    "Presence": "WAWebPresenceChatAction",
    "ChatState": "WAWebChatStateBridge",
    "CommonGroups": "WAWebFindCommonGroupsContactAction.findCommonGroups",
    "StatusUtils": "WAWebContactStatusBridge",
    "MessageLoader": "WAWebChatLoadMessages",
    "ReactionSender": "WAWebSendReactionMsgAction.sendReactionToMsg",
    "ReactionsDB": "WAWebDBCreateOrUpdateReactions",
    "EphemeralMessages": "WAWebGetEphemeralFieldsMsgActionsUtils",
    "MessageChecks": "WAWebMsgActionCapability",
    "QuotedMsgUtils": "WAWebQuotedMsgModelUtils",
    "LinkPreview": "WAWebLinkPreviewChatAction",
    "SocketDeprecated": "WADeprecatedSendIq",
    "SocketWap": "WAWap",
    "MessageSearch": "WAWebChatMessageSearch",
    "DrawerManager": "WAWebDrawerManager.DrawerManager",
    "ContactAPI": "WAWebApiContact",
    "WidToJid": "WAWebWidToJid",
    "JidToWid": "WAWebJidToWid",
    "MessageInfo": "WAWebApiMessageInfoStore.queryMsgInfo",
    "CheckExist": "WAWebQueryExistsJob.queryWidExists",
    "ReplyUtils": "WAWebMsgReply",
    "BotSecret": "WAWebBotMessageSecret",
    "BotProfiles": "WAWebBotProfileCollection",
    "Contacts": "WAWebContactCollection.ContactCollection",
    "Devices": "WAWebApiDeviceList",
    "HistorySync": "WAWebSendNonMessageDataRequest",
    "ReactionTable": "WAWebAddonReactionTableMode.reactionTableMode",
    "PollVoteTable": "WAWebAddonPollVoteTableMode.pollVoteTableMode",
    "PinChat": "WAWebSendPinMessageAction",
    "ChatGetters": "WAWebChatGetters",
    "UploadManager": "WAWebUploadManager",
    "StreamModel": "WAWebStreamModel",
    "ChatFinder": "WAWebFindChatAction",
}


WAWEB_CONTACT_GETTERS = [
    "getBusinessProfile",
    "getCalculatedStatusMute",
    "getCanRequestPhoneNumber",
    "getContactUnsafe",
    "getHeader",
    "getId",
    "getIsBot",
    "getIsBroadcast",
    "getIsBusiness",
    "getIsCAPISupportAccount",
    "getIsDisplayNameApproved",
    "getIsEnterprise",
    "getIsGroup",
    "getIsHosted",
    "getIsIAS",
    "getIsMe",
    "getIsMyContact",
    "getIsNewsletter",
    "getIsNonVerified",
    "getIsPSA",
    "getIsSmb",
    "getIsSupportAccount",
    "getIsUser",
    "getIsWAContact",
    "getLabels",
    "getMentionName",
    "getName",
    "getNotifyName",
    "getParentStatusMute",
    "getPremiumMessageName",
    "getPrivacyMode",
    "getPushname",
    "getRequestedPnTimestamp",
    "getSearchVerifiedName",
    "getShortName",
    "getShouldForceBusinessUpdate",
    "getShowAsMetaVerified",
    "getShowBiz3pBotVerifiedNameAsSecondary",
    "getShowBusinessCheckmarkAsPrimary",
    "getShowBusinessCheckmarkAsSecondary",
    "getShowBusinessCheckmarkInChatlist",
    "getStatusMute",
    "getUserhash",
    "getUserid",
    "getVerifiedLevel",
    "getVerifiedName"
]
